export type * from './domain/models.ts'
export type * from './protocol/contracts.ts'
export { ClientError } from './domain/errors.ts'
export type { ClientErrorCode } from './domain/errors.ts'
export type * from './ports/gateways.ts'
export type * from './ports/platform.ts'
export type * from './ports/durableInbox.ts'
export { DeviceIdentityService, isDeviceIdentity } from './auth/deviceIdentity.ts'
export { createSessionStore } from './auth/sessionStore.ts'
export type { SessionState, SessionStore, SessionStoreDependencies } from './auth/sessionStore.ts'
export { ChatPreferencesService } from './chats/chatPreferences.ts'
export { createChatStore } from './chats/chatStore.ts'
export type { ChatState, ChatStore, ChatStoreDependencies } from './chats/chatStore.ts'
export { MessengerService } from './messaging/messengerService.ts'
export { SyncManager } from './messaging/syncManager.ts'
export type { MailboxLoadResult } from './messaging/messengerService.ts'
export { PlaintextMessageCodec } from './messaging/messageCodec.ts'
export type { IncomingEnvelope, MessageCodec } from './messaging/messageCodec.ts'
export { mergeMessages } from './messaging/messageState.ts'
